// AUTO-GENERATED — DO NOT EDIT
// Generated by tools/sdlc.js from the service's .sdl definition.
// Re-run `npm run gen` to regenerate.

import ClientRSI from './ClientRSI.js';

export default class ProxyCriminal extends ClientRSI {
    constructor(host, port, options = {}) {
        super(host, port, options);
    }

    /**
     * create — Criminal service (remote call).
     * @param {Object} args
     * @param {string} args.full_name
     * @param {string} [args.alias]
     * @param {string} [args.nationality]
     * @param {string} args.crime
     * @param {number} [args.danger_level]
     * @param {boolean} [args.captured]
     * @returns {Promise<{ msg: string, result: Object|null }>} Criminal
     */
    async create(args) {
        return this.sendBO({ className: 'Criminal', method: 'create', args });
    }

    /**
     * getById — Criminal service (remote call).
     * @param {number} id
     * @returns {Promise<{ msg: string, result: Object|null }>} Criminal
     */
    async getById(id) {
        return this.sendBO({ className: 'Criminal', method: 'getById', args: { id } });
    }

    /**
     * list — Criminal service (remote call).
     * @param {Object} [args]
     * @param {number} [args.limit]
     * @param {number} [args.offset]
     * @returns {Promise<{ msg: string, result: Object[]|null }>} Criminal[]
     */
    async list(args = {}) {
        return this.sendBO({ className: 'Criminal', method: 'list', args });
    }

    /**
     * search — Criminal service (remote call).
     * @param {string} q
     * @returns {Promise<{ msg: string, result: Object[]|null }>} Criminal[]
     */
    async search(q) {
        return this.sendBO({ className: 'Criminal', method: 'search', args: { q } });
    }

    /**
     * update — Criminal service (remote call).
     * @param {Object} args
     * @param {number} args.id
     * @param {string} [args.full_name]
     * @param {string} [args.alias]
     * @param {string} [args.nationality]
     * @param {string} [args.crime]
     * @param {number} [args.danger_level]
     * @param {boolean} [args.captured]
     * @returns {Promise<{ msg: string, result: Object|null }>} Criminal
     */
    async update(args) {
        return this.sendBO({ className: 'Criminal', method: 'update', args });
    }

    /**
     * remove — Criminal service (remote call).
     * @param {number} id
     * @returns {Promise<{ msg: string, result: Object|null }>} Criminal
     */
    async remove(id) {
        return this.sendBO({ className: 'Criminal', method: 'remove', args: { id } });
    }
}
