INSERT INTO criminals (full_name, alias, nationality, crime, danger_level, captured) VALUES
  ('Joaquin Archivaldo Guzman Loera',  'El Chapo',          'Mexican',      'drug trafficking',              5, true),
  ('Pablo Emilio Escobar Gaviria',     'El Patron',         'Colombian',    'drug trafficking, murder',      5, true),
  ('Amado Carrillo Fuentes',           'Lord of the Skies', 'Mexican',      'drug trafficking',              5, true),
  ('Miguel Angel Felix Gallardo',      'El Padrino',        'Mexican',      'drug trafficking, corruption',  5, true),
  ('Ivan Archivaldo Guzman Salazar',   'El Chapito',        'Mexican',      'drug trafficking, extortion',   5, false),
  ('Ismael Zambada Garcia',            'El Mayo',           'Mexican',      'drug trafficking, money laundering', 5, false),
  ('Nemesio Oseguera Cervantes',       'El Mencho',         'Mexican',      'drug trafficking, murder',      5, false),
  ('Rafael Caro Quintero',             'El Narco de Narcos','Mexican',      'drug trafficking, murder',      4, false),
  ('Juan Jose Esparragoza Moreno',     'El Azul',           'Mexican',      'drug trafficking',              4, true),
  ('Gilberto Rodriguez Orejuela',      'El Ajedrecista',    'Colombian',    'drug trafficking, money laundering', 4, true),
  ('Miguel Rodriguez Orejuela',        NULL,                'Colombian',    'drug trafficking',              4, true),
  ('Diego Fernando Murillo Bejarano',  'Don Berna',         'Colombian',    'paramilitary, murder',          4, true),
  ('Juan Carlos Ramirez Abadia',       'Chupeta',           'Colombian',    'drug trafficking',              4, true),
  ('Dairo Antonio Usuga David',        'Otoniel',           'Colombian',    'drug trafficking, terrorism',   5, true),
  ('Carlos Lehder Rivas',              NULL,                'Colombian',    'drug trafficking',              4, true),
  ('Khun Sa',                          'The Opium King',    'Burmese',      'drug trafficking',              5, true),
  ('Frank Lucas',                      'Superfly',          'American',     'drug trafficking, bribery',     3, true),
  ('Griselda Blanco',                  'La Madrina',        'Colombian',    'drug trafficking, murder',      4, true),
  ('El Señor de los Cielos Jr',        'Amado Jr',          'Mexican',      'drug trafficking',              3, false),
  ('Fausto Isidoro Moran Rodriguez',   'El Fino',           'Ecuadorian',   'drug trafficking, extortion',   4, false),
  ('Rodrigo Londono Echeverri',        'Timochenko',        'Colombian',    'insurgency, kidnapping',        4, true),
  ('Lucchino Borrelli',                'Lucky Lucho',       'Italian',      'mafia, extortion, fraud',       3, true),
  ('Al Capone',                        'Scarface',          'American',     'racketeering, tax evasion',     4, true),
  ('Benjamin Siegel',                  'Bugsy',             'American',     'murder, illegal gambling',      4, true),
  ('Charles Luciano',                  'Lucky Luciano',     'Italian',      'racketeering, prostitution',    5, true),
  ('Meyer Lansky',                     'The Mob Accountant','American',     'money laundering, illegal gambling', 4, true),
  ('Frank Costello',                   'The Prime Minister','American',     'racketeering, corruption',      3, true),
  ('Carlo Gambino',                    NULL,                'Italian',      'racketeering, murder',          5, true),
  ('John Gotti',                       'The Teflon Don',    'American',     'racketeering, murder',          4, true),
  ('Salvatore Gravano',                'Sammy the Bull',    'American',     'murder, racketeering',          3, true),
  ('Nikolas Petrakis',                 'El Griego',         'Greek',        'human trafficking, fraud',      3, false),
  ('Ivan Drago Volkov',                'The Bear',          'Russian',      'arms dealing, cyberattacks',    5, false),
  ('Sergei Popkov',                    NULL,                'Russian',      'serial murder',                 5, true),
  ('Viktor Bout',                      'Merchant of Death', 'Russian',      'arms trafficking',              4, true),
  ('Semion Mogilevich',                'The Boss of Bosses','Ukrainian',    'organized crime, fraud',        5, false),
  ('Yamaguchi Kenji',                  'Tetsu',             'Japanese',     'yakuza, extortion, gambling',   4, false),
  ('Takashi Mori',                     NULL,                'Japanese',     'yakuza, protection racket',     3, true),
  ('Zhou Wei',                         'Dragon Head',       'Chinese',      'human trafficking, counterfeit',4, false),
  ('Liang Chen',                       'The Broker',        'Chinese',      'cybercrime, fraud',             3, false),
  ('Ahmad Khalil',                     'The Ghost',         'Lebanese',     'money laundering, counterfeiting', 4, false),
  ('Hassan Nasrallah Jr',              NULL,                'Lebanese',     'arms trafficking, extortion',   3, false),
  ('Mohamed Al-Rashid',                'The Accountant',    'Saudi',        'financial fraud, bribery',      3, false),
  ('Tiago Barbosa',                    'Tio Tiago',         'Brazilian',    'drug trafficking, murder',      4, false),
  ('Luiz Fernando da Costa',           'Fernandinho Beira-Mar', 'Brazilian','drug trafficking',              5, true),
  ('Marco Antonio Lima',               NULL,                'Brazilian',    'kidnapping, extortion',         3, true),
  ('Roberto Esparza',                  'El Profesor',       'Venezuelan',   'drug trafficking, corruption',  4, false),
  ('Carlos Ortiz Torres',              'El Cachorro',       'Honduran',     'drug trafficking, murder',      4, false),
  ('Juan Pedro Salinas',               'El Gordo',          'Guatemalan',   'drug trafficking, extortion',   3, false),
  ('Renato Valenzuela',                'El Raton',          'Chilean',      'fraud, money laundering',       2, true),
  ('Diego Armando Calderon',           'El Toro',           'Peruvian',     'drug trafficking, corruption',  3, false),
  ('Federica Moretti',                 'La Serpiente',      'Italian',      'mafia, extortion',              3, false),
  ('Christophe Beaumont',              NULL,                'French',       'organized crime, fraud',        2, true),
  ('Dmitri Voloshyn',                  'The Hammer',        'Ukrainian',    'cybercrime, ransomware',        4, false),
  ('Oleg Grigoriev',                   'Grisha',            'Russian',      'arms dealing, money laundering',3, false),
  ('Ali Hassan Karimi',                'El Persa',          'Iranian',      'sanctions evasion, arms trafficking', 4, false),
  ('Tariq Nawaz',                      NULL,                'Pakistani',    'drug trafficking, terrorism financing', 4, false),
  ('Pradeep Kumar Singh',              'The Tiger',         'Indian',       'organized crime, extortion',    3, false),
  ('Jafar Rahimi',                     'The Fixer',         'Afghan',       'heroin trafficking, corruption',4, false),
  ('Emilio Sandoval',                  'El Sombra',         'Mexican',      'kidnapping, extortion',         3, false),
  ('Roberto Alvarado',                 'El Brujo',          'Salvadoran',   'murder, gang leadership',       4, false),
  ('Alejandro Reyes',                  'El Fantasma',       'Colombian',    'drug trafficking, murder',      4, false);
