// Proxy generator: emitProxy(ast) -> string for client/Proxy<Service>.js.
//
// Each service becomes a class extending ClientRSI (default import). Every
// method is emitted following the arity rule from ast.classifyArity:
//   positional (1 param) -> method(<param>) wrapping into args: { <param> }
//   object (0 or 2+ params) -> method(args) passing the object straight through.
//
// For object-form methods whose params are ALL optional (or none), the
// signature gets an `args = {}` default so the method is callable with no
// arguments — reproducing the existing `list(args = {})` convention while
// `create(args)` / `update(args)` (which have required params) stay bare.

import { classifyArity, typeToString } from './ast.js'

const BANNER = `// AUTO-GENERATED — DO NOT EDIT
// Generated by tools/sdlc.js from the service's .sdl definition.
// Re-run \`npm run gen\` to regenerate.`

// SDL scalar type -> JSDoc/JS type. Unknown idents (e.g. a domain type like
// Criminal) map to Object — JS has no nominal type for them at runtime.
const JSDOC_TYPES = {
  string: 'string',
  int: 'number',
  float: 'number',
  number: 'number',
  bool: 'boolean',
  boolean: 'boolean',
  json: 'Object',
  any: '*',
  void: 'void',
}

function jsType(type) {
  if (!type) return '*'
  const base = JSDOC_TYPES[type.name] ?? 'Object'
  return type.array ? `${base}[]` : base
}

// The BO envelope is always { msg: string, result: <T>|null } (result is null
// on error), so the @returns reflects that, annotated with the SDL return type.
function returnsTag(method) {
  const result = method.returns ? `${jsType(method.returns)}|null` : '*'
  const label = typeToString(method.returns)
  const suffix = label ? ` ${label}` : ''
  return `     * @returns {Promise<{ msg: string, result: ${result} }>}${suffix}`
}

function jsdoc(service, method) {
  const lines = [
    `    /**`,
    `     * ${method.name} — ${service.name} service (remote call).`,
  ]

  if (classifyArity(method) === 'positional') {
    const p = method.params[0]
    lines.push(`     * @param {${jsType(p.type)}} ${p.name}`)
  } else {
    const optionalObj = method.params.length === 0 || allOptional(method)
    lines.push(`     * @param {Object}${optionalObj ? ' [args]' : ' args'}`)
    for (const p of method.params) {
      const name = p.type.optional ? `[args.${p.name}]` : `args.${p.name}`
      lines.push(`     * @param {${jsType(p.type)}} ${name}`)
    }
  }

  lines.push(returnsTag(method))
  lines.push(`     */`)
  return lines.join('\n')
}

function allOptional(method) {
  return method.params.every((p) => p.type.optional)
}

function emitMethod(service, method) {
  const arity = classifyArity(method)
  const doc = jsdoc(service, method)

  if (arity === 'positional') {
    const param = method.params[0].name
    return [
      doc,
      `    async ${method.name}(${param}) {`,
      `        return this.sendBO({ className: '${service.name}', method: '${method.name}', args: { ${param} } });`,
      `    }`,
    ].join('\n')
  }

  // object form
  const sig = allOptional(method) ? 'args = {}' : 'args'
  return [
    doc,
    `    async ${method.name}(${sig}) {`,
    `        return this.sendBO({ className: '${service.name}', method: '${method.name}', args });`,
    `    }`,
  ].join('\n')
}

function emitService(service) {
  const className = `Proxy${service.name}`
  const methods = service.methods.map((m) => emitMethod(service, m)).join('\n\n')

  return [
    BANNER,
    ``,
    `import ClientRSI from './ClientRSI.js';`,
    ``,
    `export default class ${className} extends ClientRSI {`,
    `    constructor(host, port, options = {}) {`,
    `        super(host, port, options);`,
    `    }`,
    ``,
    methods,
    `}`,
    ``,
  ].join('\n')
}

export function emitProxy(ast) {
  if (!ast || !Array.isArray(ast.services) || ast.services.length === 0) {
    throw new Error('emitProxy(ast): AST has no services')
  }
  if (ast.services.length > 1) {
    throw new Error(
      'emitProxy(ast): expected a single service per proxy file; got ' +
        ast.services.map((s) => s.name).join(', '),
    )
  }
  return emitService(ast.services[0])
}
